WIFI/ENDPOINT SETUP
extremeprogamers/fridge-board pull request #1
Opened 2019-06-04 20:13 UTC by siorekoskar

Initial wifi setup on softAP and first endpoint

2019-06-04 20:22 UTC, Mefffiu requested changes
Please, remove unused dependencies and apply shared coding rules.

2019-06-04 20:22 UTC, Mefffiu commented on platformio.ini
> +    ESP Async WebServer
Can be removed.

2019-06-04 20:22 UTC, Mefffiu commented on src/main.cpp
> +{
`{` should be in the same line as `void handleRoot()`

2019-06-04 20:22 UTC, Mefffiu commented on src/main.cpp
> +void setup()
`{` should be in the same line as `void setup()`

2019-06-04 20:22 UTC, Mefffiu commented on src/main.cpp
> +  {
`{` should be in line 26

2019-06-04 20:22 UTC, Mefffiu commented on src/main.cpp
> +  {
`{` should be in line 31

2019-06-04 20:22 UTC, Mefffiu commented on src/main.cpp
> +{
`{` should be in line 40

2019-06-05 18:06 UTC, siorekoskar commented on src/main.cpp
> +{
done

2019-06-05 18:06 UTC, siorekoskar commented on src/main.cpp
> +  {
done

2019-06-05 18:06 UTC, siorekoskar commented on src/main.cpp
> +  {
done

2019-06-05 18:06 UTC, siorekoskar commented on src/main.cpp
> +void setup()
done

2019-06-05 18:06 UTC, siorekoskar commented on src/main.cpp
> +{
done

2019-06-05 18:07 UTC, siorekoskar commented on platformio.ini
> +    ESP Async WebServer
done

2019-06-05 18:09 UTC, merged